#!/bin/bash 
#SBATCH -J labelling
#SBATCH -o /share/ju/matt/bayflood/.slurm_jobs/labelling-server/%j.out
#SBATCH -e /share/ju/matt/bayflood/.slurm_jobs/labelling-server/%j.err
#SBATCH --mail-type=ALL 
#SBATCH --mail-user=mwf62@cornell.edu 
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --get-user-env 
#SBATCH --mem=32gb
#SBATCH -t 240:00:00
#SBATCH --partition=ju

pwd
source /home/mwf62/.bashrc
 
cd /share/pierson/matt/mllmsci
source .venv/bin/activate

# add label-studio to python path
#export PYTHONPATH=$PYTHONPATH:/share/ju/urban-fingerprinting/src/utils/labelling/label-studio

label-studio --port 8925